shell fish
font_family JetBrainsMono Nerd Font
font_size 11.5
background_opacity 0.55
dynamic_background_opacity yes
window_padding_width 8
confirm_os_window_close 0
window_padding_width 8
hide_window_decorations no

# ---

# shell fish

# font_family JetBrainsMono Nerd Font
# background_opacity 0.4
# background_blur 1
# window_padding_width 8
# cursor_shape beam

# shell /usr/bin/zsh
